services:
  kishop:
    build: .
    container_name: kishop
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/shopping.db
      - PORT=3001
    networks:
      - linuxserver

networks:
  linuxserver:
    external: true

