services:
  kishop:
    build: .
    container_name: kishop
    restart: unless-stopped
    ports:
      # - "${HTTP_PORT:-80}:80"
      # - "${HTTPS_PORT:-443}:443"
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - HTTP_PORT=${HTTP_PORT:-80}
      - HTTPS_PORT=${HTTPS_PORT:-443}
    networks:
      - kishop-network

networks:
  default:
    name: linuxserver
    external: true
      
